#!/usr/bin/env node
// Generates the film timeline from scenes.json:
//   src/film.ts            canvas, fps, bpm, duration, audio flag
//   src/timeline.ts        SCENE_TIMES (+ hand-off mode per scene), SceneProps, at()
//   src/scenes/SNN.tsx     placeholder for every scene that doesn't exist yet (never overwrites real work)
//   src/scenes/index.ts    scene registry
//   src/entries/SNN.tsx    isolated per-scene entry points (so one broken scene can't break another's renders)
// Re-run any time scenes.json changes (e.g. after adding audio: set "audio": true).
import fs from 'fs';
import path from 'path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const cfg = JSON.parse(fs.readFileSync(path.join(root, 'scenes.json'), 'utf8'));
const { fps = 30, width = 1920, height = 1080, bpm = 120, duration, audio = false, scenes } = cfg;
if (!Array.isArray(scenes) || !scenes.length) throw new Error('scenes.json: "scenes" is empty');

// ---- validate: contiguous, ordered, ids unique, last scene ends at duration
const ids = new Set();
scenes.forEach((s, i) => {
  if (!/^S\d{2}$/.test(s.id)) throw new Error(`scene id must look like S01: ${s.id}`);
  if (ids.has(s.id)) throw new Error(`duplicate scene id ${s.id}`);
  ids.add(s.id);
  if (!(s.end > s.start)) throw new Error(`${s.id}: end must be > start`);
  if (i > 0 && Math.abs(scenes[i - 1].end - s.start) > 1e-6) throw new Error(`${s.id}: starts at ${s.start} but previous ends at ${scenes[i - 1].end} (scenes must be contiguous)`);
  if (!['dip', 'xfade', 'cut'].includes(s.handoff ?? 'dip')) throw new Error(`${s.id}: handoff must be dip | xfade | cut`);
});
const total = duration ?? scenes[scenes.length - 1].end;
if (Math.abs(scenes[scenes.length - 1].end - total) > 1e-6) throw new Error(`last scene must end at duration (${total})`);
const beat = 60 / bpm;
const offGrid = scenes.filter((s) => Math.abs(s.start / beat - Math.round(s.start / beat)) > 1e-6).map((s) => s.id);
if (offGrid.length) console.warn(`warning: scenes not starting on a beat (${beat}s): ${offGrid.join(', ')}`);
if (audio && !fs.existsSync(path.join(root, 'public', 'audio', 'score.wav'))) console.warn('warning: "audio": true but public/audio/score.wav does not exist yet');

const write = (rel, text) => { fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true }); fs.writeFileSync(path.join(root, rel), text); };

write('src/film.ts', `// GENERATED by tools/scaffold.mjs from scenes.json — do not edit by hand.
export const FILM = { fps: ${fps}, width: ${width}, height: ${height}, bpm: ${bpm}, duration: ${total}, audio: ${!!audio} } as const;
`);

const rows = scenes.map((s) => `  ${s.id}: { start: ${s.start}, end: ${s.end}, title: ${JSON.stringify(s.title ?? s.id)}, handoff: '${s.handoff ?? 'dip'}' as Handoff${s.exit ? `, exit: ${s.exit}` : ''} },`).join('\n');
write('src/timeline.ts', `// GENERATED by tools/scaffold.mjs from scenes.json — do not edit by hand.
import { FILM } from './film';

export type Handoff = 'dip' | 'xfade' | 'cut';
export type SceneWindow = { start: number; end: number; title: string; handoff: Handoff; exit?: number };

/** Absolute scene windows in seconds (see ../STORYBOARD.md). */
export const SCENE_TIMES = {
${rows}
} satisfies Record<string, SceneWindow>;
export type SceneId = keyof typeof SCENE_TIMES;
export const SCENE_IDS = Object.keys(SCENE_TIMES) as SceneId[];

/** Each scene is authored against nominal length + TAIL frames (none for the last scene). */
export const TAIL = 10;

/** Props every scene receives. \`dur\` = authored length in frames, \`start\` = absolute start in seconds. */
export type SceneProps = { dur: number; start: number };

/** Absolute seconds -> local frame within a scene that starts at \`start\` seconds. */
export const at = (abs: number, start: number) => Math.round((abs - start) * FILM.fps);

export const HAS_AUDIO = FILM.audio;
`);

for (const s of scenes) {
  const f = `src/scenes/${s.id}.tsx`;
  if (!fs.existsSync(path.join(root, f))) {
    write(f, `import React from 'react';
import { Backdrop, Center, MonoLabel, SceneEnvelope, Words } from '../design/primitives';
import { SceneProps } from '../timeline';

// PLACEHOLDER — replace with the real scene (see STORYBOARD.md and BUILD_GUIDE.md).
export const ${s.id}: React.FC<SceneProps> = ({ dur }) => (
  <SceneEnvelope dur={dur} inDur={10} outDur={0}>
    <Backdrop />
    <Center style={{ flexDirection: 'column', gap: 18 }}>
      <MonoLabel size={22}>${s.id} · ${(s.title ?? '').replace(/[`$\\]/g, '')}</MonoLabel>
      <Words text="Placeholder [scene]." size={72} start={4} />
    </Center>
  </SceneEnvelope>
);
`);
    console.log('created', f);
  }
}

write('src/scenes/index.ts', `// GENERATED by tools/scaffold.mjs — do not edit by hand.
import React from 'react';
import { SceneId, SceneProps } from '../timeline';
${scenes.map((s) => `import { ${s.id} } from './${s.id}';`).join('\n')}

export const SCENES: Record<SceneId, React.FC<SceneProps>> = { ${scenes.map((s) => s.id).join(', ')} };
`);

scenes.forEach((s, i) => {
  const last = i === scenes.length - 1;
  write(`src/entries/${s.id}.tsx`, `// GENERATED by tools/scaffold.mjs — isolated entry: bundles ONLY ${s.id}.
import React from 'react';
import { Composition, registerRoot } from 'remotion';
import { FILM } from '../film';
import { SCENE_TIMES${last ? '' : ', TAIL'} } from '../timeline';
import { ${s.id} } from '../scenes/${s.id}';
import '../design/fonts';

const t = SCENE_TIMES.${s.id};
const len = Math.round((t.end - t.start) * FILM.fps)${last ? '' : ' + TAIL'};
const Wrapped: React.FC = () => <${s.id} dur={len} start={t.start} />;
registerRoot(() => <Composition id="${s.id}" component={Wrapped} durationInFrames={len} fps={FILM.fps} width={FILM.width} height={FILM.height} />);
`);
});

console.log(`scaffolded ${scenes.length} scenes · ${total}s @ ${fps}fps · ${bpm} BPM (beat ${Math.round(beat * fps)} f) · audio ${audio ? 'on' : 'off'}`);
